In [65]:
import numpy as np

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [66]:
array = np.arange(1,10)
array[array%2==1] 

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [67]:
np.where(array%2==1,0,array)

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
temp = np.genfromtxt(url, delimiter=',')
iris = temp[:,:4]
print(iris[:10,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [69]:
#Média
iris[:,0].mean()

5.843333333333334

In [70]:
#Mediana
np.median(iris[:,0])

5.8

In [71]:
#Desvio padrão
iris[:,0].std()

0.8253012917851409

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [72]:
iris[(iris[:,2]>1.5) & (iris[:,0]<5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [73]:
np.isnan(iris).sum()
#Não possui 'nans'

0

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [74]:
np.set_printoptions(precision=2)

In [75]:
volume = np.pi*iris[:,2]*iris[:,0]**2/3

volume = volume.reshape(150,1)

iris = np.hstack([iris, volume])
print(iris[:10])

[[ 5.1   3.5   1.4   0.2  38.13]
 [ 4.9   3.    1.4   0.2  35.2 ]
 [ 4.7   3.2   1.3   0.2  30.07]
 [ 4.6   3.1   1.5   0.2  33.24]
 [ 5.    3.6   1.4   0.2  36.65]
 [ 5.4   3.9   1.7   0.4  51.91]
 [ 4.6   3.4   1.4   0.3  31.02]
 [ 5.    3.4   1.5   0.2  39.27]
 [ 4.4   2.9   1.4   0.2  28.38]
 [ 4.9   3.1   1.5   0.1  37.71]]
