# NumPy

## O que é o NumPy?

O NumPy é uma poderosa biblioteca Python usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações prontas que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* `Tarefas matemáticas`: NumPy é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação, extrapolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. É uma biblioteca que pode ser usada em conjuto do <a href='https://github.com/scipy/scipy'>SciPy</a> e Matplotlib, substituindo o MATLAB quando se trata de tarefas matemáticas.

* `Processamento de Imagem e Computação Gráfica`: Imagens no computador são representadas como Arrays Multidimensionais de números. NumPy torna-se a escolha mais natural para o mesmo. O NumPy, na verdade, fornece algumas excelentes funções para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

* `Modelos de Machine Learning`: Ao escrever algoritmos de Machine Learning, supõe-se que se realize vários cálculos numéricos em Array. Por exemplo, multiplicação de Arrays, transposição, adição, etc. O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (em termos de velocidade). Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.


## Instalando

Existem diversas formas de instalar o numpy. A mais simples é instalar o pacote Anaconda (https://www.anaconda.com/distribution/) que já vem com o Python e diversas bibliotecas científicas e ciência de dados instaladas.

Outra forma, caso você já tenha o python instalado mas não o numpy, é o utilizar o gerenciador e pacotes pip, através do comando no seu **terminal**:

`$ pip install numpy`

ou dentro do jupyter

`!pip install numpy`

## Explorando a API do NumPy
### Importando numpy com o alias np

`np` é uma abreviação amplamente utilizada na comunidade python para o numpy.

In [1]:
import numpy as np

### 1D arrays

Array unidimensional, também chamado de vetor ou até mesmo matriz de 1 dimensão:


In [32]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Checando o tipo da variável a:

In [3]:
type(a)

numpy.ndarray

o ndarray significa n-dimensional array


### Checando o tipo de dados do array

Diversos tipos de dados são possíveis em um array numpy, os mais comuns são os numéricos:

    int32
    int64
    float32
    float64


In [4]:
a.dtype

dtype('int32')

### Substituindo elementos
Se trocarmos o elemento na posição 0 para o valor 10, dará certo:

In [9]:
a[0] = 10
a

array([10,  2,  3])

Mas, se trocarmos para ponto flutuante, por exemplo 1.2, o numpy irá truncar a parte decimal, dado que o array que criamos é de inteiros.

In [10]:
a[0] = 1.2
a

array([1, 2, 3])

E se quisermos um dos elementos sendo um texto como fazíamos com as listas?

In [11]:
lista = [1, 2, 'LC', 4]
array = np.array([1, 2, 'LC', 4])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

Essa é a lista:  [1, 2, 'LC', 4]
Esse é o array:  ['1' '2' 'LC' '4']


O array converte todos os elementos para string. O numpy não aceita dados com tipos diferentes. Ter um tipo único, permite o numpy ser muito mais rápido.

### Porque usar numpy e não listas?
#### Numpy x Lists

    Tamanho - Numpy necessita de menos espaço
    Performance - escrito para ter alta performance
    Funcionalidade - SciPy e NumPy possuem operações de algebra linear built in.

<a href="https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference" target="_blank">Referência</a> 

#### Tempo de processamento

In [19]:
"""
Código comparando performance entre numpy e listas em uma soma de arrays
"""

import time
import numpy as np

size_of_vec = 100000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.01996898651123047 0.0009715557098388672
Numpy is in this example 20.55361963190184 faster!


#### Diferença visual

In [23]:
lista = [1, 2, 3, 4]
array = np.array([1, 2, 3, 4])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

Essa é a lista:  [1, 2, 3, 4]
Esse é o array:  [1 2 3 4]


Repare que no array não temos a separação por vírgulas.
<br>



### 2D arrays

Matrizes podem ser consideradas um array de 2 dimensões.
_________________________________________________________________________________

Observação:

O NumPy possui também uma estrutura, `np.matriz`, mas não é recomendado utilizá-la pela própria documentação oficial e poderá ser removida no futuro.
_________________________________________________________________________________


Para criar uma matriz, 
$$\begin{bmatrix} 9.0 & 8.0 & 7.0 \\ 6.0 & 5.0 & 4.0 \end{bmatrix}$$ <br>
basta aninhar múltiplas listas dentro de uma lista, como o exemplo a seguir:


In [24]:
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


____________
____________
**Exercício:** Crie em numpy a seguinte matriz:
$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

In [33]:
# Resposta
a = np.array([[1,2,1],
              [3,0,1],
              [0,2,4]])
print(a)

[[1 2 1]
 [3 0 1]
 [0 2 4]]


_______________
_______________

### 3D arrays

Nesse caso, teremos um tensor tridimensional que visualmente pode ser interpretado das seguintes formas:


<img src="tensor_3-2-5.png"  style="width: 500px" />

In [28]:
c = np.array([[[0,   1,  2,  3,  4], [ 5,  6,  7,  8,  9]], 
              [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
              [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]])
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [29]:
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


### Propriedades
#### Dimensão e formato

Três conceitos importantes, já mencionados acima, são os de dimensão, formato e tamanho.

Para descobrir essas informações, basta acessar os atributos `ndim`, `shape` e `size`

In [37]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)
print(a.size)

1
(3,)
3


In [35]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(2, 3)
6


In [38]:
len(b)

2

In [36]:
print(c.ndim)
print(c.shape)
print(c.size)

3
(3, 2, 5)
30


In [39]:
len(c)

3

### Acessando e modificando elementos (Indexing & Slicing)

Dada a matriz a abaixo:

In [40]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19, 20, 21]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]



Podemos acessar um elemento específico do vetor de forma similar a lista. A diferença é que podemos escolher um elemento específico passando os índices de linha e coluna: <br> <br>
**array[Indice_Linha, Indice_Coluna]**
<br><br>

Para uma array 2D, a sintaxe fica:


In [41]:
a[2,4]

19

Podemos também fazer da forma **array[Indice_Linha][Indice_Coluna]** (menos comum):

In [42]:
a[2][4]

19

No caso acima, primeiro selecionamos toda a linha para depois selecionar a coluna de interesse.
<br><br><br>
Assim como nas listas, **números negativos** trazem de trás pra frente a indexação:


In [45]:
a[2,-2]

20

Para selecionar todos os dados de uma coluna específica utilizamos o `:` na posição das linhas.

Leia-se: todas as linhas, coluna 2


In [46]:
a[:,2]

array([ 3, 10, 17])

In [47]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

O operador `:` também conhecido como slicing, aceita o parâmetro:

    start
    end
    step

No formato

$ [ startindex : endindex : stepsize ] $ 

O stepsize basicamente é quantos elementos deve ser pular. Podemos pegar do elemento 1 ao 6 pulando de 2 em 2 por exemplo da linha 0.


In [49]:
a[0,0:6:2]

array([1, 3, 5])

Funciona com negativo também:


In [50]:
# negativo na coluna
a[0, 1:-1:2]

array([2, 4, 6])

In [51]:
# negativo no step
a[0, -1:1:-2]

array([7, 5, 3])

Para mudar um elemento específico, basta usar o operador `=`

In [52]:
a[0,2] = 99

In [53]:
print(a)

[[ 1  2 99  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


Mudando uma coluna inteira para ser 5:


In [54]:
a[:,1] = 5
a

array([[ 1,  5, 99,  4,  5,  6,  7],
       [ 8,  5, 10, 11, 12, 13, 14],
       [15,  5, 17, 18, 19, 20, 21]])

Isso mostra uma característica fundamental do array do NumPy:

  *Ao alterar o pedaço da matriz recortada, você altera a matriz original enquanto slicing em listas geram cópias!*

### Cópias do array

Um dos detalhes do numpy é que se você faz um slice do array você não obtém um vetor totalmente novo. A saída é uma "view" do array original.

Esse é o mesmo conceito de que as variáveis são apenas ponteiros e que variáveis distintas podem apontar para o mesmo objeto. (<a href="https://www.practicaldatascience.org/html/exercises/%5B../python_v_r.ipynb%5D">Python v. R / Variables as Pointers tutorial</a>). No caso de slices, as duas variáveis acessam o mesmo dado, mas apresentam ele de form distinta. Por exemplo:


In [55]:
my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [56]:
my_slice = my_array[1:3]
my_slice

array([2, 3])

Uma vez que tanto my_array quanto my_slice apontam para o mesmo dado, mudanças que fizermos em um será propagada para o outro. Se modificarmos a entrada 2 no my_slice, essa mudança irá aparecer no my_array:

In [57]:
my_slice[0]

2

In [58]:
my_slice[0] = -1
my_slice

array([-1,  3])

In [59]:
my_array

array([ 1, -1,  3,  4])

Apesar de o my_array e o my_slice estarem acessando o mesmo dado eles estão indexados diferentes. Nós mudamos o índice 0 no my_slice e a mudança no my_array foi no índice 1. <br>
O mesmo não acontece com as listas

In [60]:
x = [1, 2, 3]
y = x[0:2]
y[0] = "a change"
y

['a change', 2]

In [61]:
x

[1, 2, 3]

Caso você não queira uma view você pode fazer o slice utilizando uma lista:

In [63]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]]
my_slice[0] = -1
my_array

array([1, 2, 3])

Ou utilizar uma cópia

In [65]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]].copy()
my_slice[0] = -1
my_array

array([1, 2, 3])

Esse último caso é o mais utilizado, inclusive com dataframes do pandas.

## Matemática


### Operação com escalares

In [77]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

#### 1. Soma

In [70]:
a + 2

array([3, 4, 5, 6])

#### 2. Subtração:


In [71]:
a - 1

array([0, 1, 2, 3])

#### 3. Multiplicação
______________
______________
**Exercício:**
Sabendo que a operação de multiplicação é feita por __*__ , multiplique o vetor *a* por 2.

In [72]:
a*2

array([2, 4, 6, 8])

#### 4. Divisão
**Exercício:**
Sabendo que a operação de divisão é feita por __/__ , divida o vetor *a* por 2.

In [73]:
a/2

array([0.5, 1. , 1.5, 2. ])

#### 5. Potência
**Exercício:**
Sabendo que a operação de potenciação é feita por __**__ , calcule o quadrado dos elementos do vetor *a*.

In [74]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

_______________________
_______________________

#### 6. Incrementar +=

In [78]:
a+=1
a

array([2, 3, 4, 5])

### Operação entre arrays

Tudo que você consegue fazer com escalar, você consegue fazer com arrays elemento-a-elemento desde que os arrays tenham exatamente o mesmo tamanho, por exemplo, para soma:


In [85]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

# Exemplo de soma
a + b

array([2, 2, 4, 4])

In [80]:
# Exemplo de multiplicação
a * b

array([1, 0, 3, 0])

In [81]:
# Exemplo de potenciação
a**b

array([1, 1, 3, 1], dtype=int32)

### Estatística

O numpy vem com várias funções básicas de estatística como mínimo, máximo, média, desvio padrão, etc.


In [86]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

Mínimo e máximo valor da matriz:

In [87]:
np.min(stats)

1

In [88]:
stats.max()

6

________________
________________
**Exercício:** encontre a média e o desvio padrão da matriz, sabendo que os métodos são representados por `np.mean()` e `np.std()`, respectivamente.

In [89]:
# média dos valores de stats
np.mean(stats)

3.5

In [92]:
stats.mean()

3.5

In [91]:
# desvio padrão dos valores de stats
np.std(stats)

1.707825127659933

In [93]:
stats.std()

1.707825127659933

_____________
_____________

Todas as vezes que tivermos mais de um eixo, poderemos especificar o argumento `axis`. Para `axis=0` a operação é feita **verticalmente para baixo ao longo das linhas**. Para `axis=1` a operação é realizada **horizontalmente entre as colunas**.

<img src="axis.jpg"  style="width: 300px" />

Mínimo para axis=0:


In [98]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.min(stats, axis=0) 

array([1, 2, 3])

In [96]:
stats.min(axis = 0)

array([1, 2, 3])

A operação será realizada ao longo dos índices.

Mínimo para axis=1:


In [95]:
np.min(stats, axis=1)

array([1, 4])

In [97]:
stats.min(axis = 1)

array([1, 4])

A operação será realizada através das colunas.

_________________
_________________
**Exercício:** Realize a soma para cada linha e para cada coluna:

In [102]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
# linha
stats.sum(axis = 1)

array([ 6, 15])

In [104]:
# coluna
stats.sum(axis = 0)

array([5, 7, 9])

___________
___________


### Máscara Booleana e Seleção Avançada

Conceito super importante no numpy e no pandas é o de máscara booleana.

Ao utilizar qualquer operador booleano

    >
    <
    <=
    >=
    ==

o numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

Suponha a matriz abaixo:


In [105]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

Eu quero saber todos os elementos maiores que 10, eu posso aplicar:


In [111]:
mat>=10

array([[False,  True],
       [ True,  True]])

O retorno é uma matriz de formato (2, 2) com True na posição dos elementos que são maiores que 10.

Os tensores booleanos podem ser usados para filtrar valores em um tensor, por exemplo:

In [110]:
mat[mat>10]

array([20, 30])

In [118]:
mat_2 = mat>10
mat*mat_2

array([[ 0,  0],
       [20, 30]])

E será retornado um array com os elementos 20 e 30 como esperado.

### Operador AND

Similar ao `and` do python, podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador `&`.


In [112]:
mat

array([[ 1, 10],
       [20, 30]])

In [113]:
filt = (mat > 10) & (mat <= 25)
mat[filt]

array([20])

Observação: note que os colchetes além de melhorarem a legibilidade, são necessárias devido a ordem de precedência dos operadores python. Se não colocarmos os colchetes, dará um erro.


### Operador OR
Similar ao `or`, só que devemos utilizar `|`. <br><br>
**Exercício:** Seleciona os valores que são iguais a 1 ou maiores do que 20


In [115]:
filt = (mat == 1) | (mat > 20)
mat[filt]

array([ 1, 30])

### Operador NOT

Similar ao `not`, mas devemos utilizar um til `~`.


In [116]:
filt = (mat > 10) & (mat <= 25)
mat[~filt]

array([ 1, 10, 30])

In [124]:
mat[~((mat > 10) & (mat <= 25))]

array([ 1, 10, 30])

### Atribuir valores em determinadas condições
E podemos também atribuir um valor específico aos elementos de um vetor que satisfazem uma certa condições, por exemplo zerar todos os valores negativos:


In [117]:
u = np.array([-1,  2, -3])
print("u =", u)
print()

u = [-1  2 -3]



In [134]:
u[u<0] = 0
u

array([0, 2, 0])

Também podemos usar o método `np.where(se condição, recebe valor, se não)`

In [119]:
np.where(u<0, 0, u)

array([0, 2, 0])

### Nans
Os **not a number** são representados por `np.nan`

In [122]:
a = np.array([[1, 2, 3, np.nan, 5], [np.nan, 7, 8, 9,10]])

Podemos identificar os nans com o método `np.isnan(a)`

In [123]:
np.isnan(a)

array([[False, False, False,  True, False],
       [ True, False, False, False, False]])

E para saber o total de nans podemos aplicar `np.isnan(a).sum()`

In [127]:
np.isnan(a).sum()

2

## Material de Aprofundamento

### Seleção passando listas

Podemos selecionar elementos específicos de um array passando uma lista de posições:


In [135]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a[[1, 2, 5, 8]]

array([2, 3, 6, 9])

### Comparando arrays

In [136]:
u = np.arange(4).reshape(2,2)
v = 2*np.ones((2,2))

In [137]:
u

array([[0, 1],
       [2, 3]])

In [138]:
v

array([[2., 2.],
       [2., 2.]])

In [ ]:
w = u > v
print(w)

In [ ]:
u[u > v]

### Reorganizar Array

Muitas vezes você quer mudar o formato de array, por exemplo, de 4 elementos pra uma matriz 2x2, ou situações similares.

Para isso, você pode utilizar a função `reshape`.


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
before

In [ ]:
after = before.reshape((4, 2)) # tem que possuir a mesma quantidade no size!
after

In [ ]:
before.reshape((-1, 2)) # o -1 representa quantas linhas for preciso para ter 2 colunas

In [ ]:
before.reshape(2, 2, 2)

### Métodos .any() e .all()
Podemos fazer operações linha a linha ou coluna a coluna através de métodos auxiliares como any ou all:

    any: se qualquer elemento da linha for True, retorna True
    all: todos os elementos tem que ser True para retornar True

Exemplos:

Por coluna:


In [ ]:
mat

In [ ]:
np.any(mat > 10, axis=0)

Por linha:

In [ ]:
np.any(mat > 10, axis=1)

Geral:

In [ ]:
np.any(mat > 10)

### Apendar os vetores
#### Verticalmente

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

#### Horizontalmente

De forma similar ao anterior:


In [ ]:
# para arrays 1D
np.hstack((v1,v2))

#### para arrays 2D

In [ ]:
h1 = np.ones((2, 4))
print(h1)
print()

h2 = np.zeros((2, 2))
print(h2)

In [ ]:
np.hstack((h1, h2))

### Números aleatórios
#### Números decimais aleatórios

O numpy tem um sub-módulo chamado random, que pode ser acessando via `np.random`. Embora o Python possua uma biblioteca padrão também chamada `random`, a biblioteca do *NumPy tem mais funcionalidades e gera diretamente vetores aleatórios*.

Cria um vetor segundo uma distribuição uniforme no intervalo [0,1):


In [ ]:
np.random.rand(4, 2)

Cria um vetor em que cada elemento segue uma distribuição normal com $\mu=10.0$ e $\sigma=1.0$

In [ ]:
v = np.random.normal(10, 1, (4,4))
print(v)


#### Números aleatórios inteiros:


Os argumentos principais são low, high e size, exemplo: criando uma matriz de 0 a 99 de 100 elementos:


In [ ]:
np.random.randint(low=0, high=100, size=100)


Para incluir o 100, basta trocar o high por 101

In [ ]:
np.random.randint(7, size=(3, 3))

Note que toda vez que rodarmos o código, os tensores terão valores diferentes. Podemos evitar esse comportamento, de forma que toda vez que o código é executado o tensor aleatório tenha o mesmo valor por meio da função seed, cujo argumento é a semente para o gerador de números aleatórios do Python:

In [ ]:
np.random.seed(1000)
v = np.random.rand(4)
print(v)

np.random.seed(1000)
v = np.random.rand(4)
print(v)


### Inicializando arrays usando métodos internos

O NumPy já possui diversos métodos built-in para gerar arrays dos mais diversos tipos
array apenas com zeros

In [ ]:
np.zeros(5)

É possível gerar um array de qualquer formato, basta apenasr passar o formato como uma sequência (lista, tupla geralmente) como argumento


In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((2, 2, 3))

array apenas com 1

In [ ]:
np.ones((4, 2, 2), dtype='int32')

Um coisa muito comum é usar o np.ones para criar uma matriz de qualquer número fazendo a operação, exemplo:

In [ ]:
np.ones((2, 2)) * 10

Mas o numpy já tem uma opção mais elegante, o full:


In [ ]:
np.full((2, 2), 99)

Qualquer outro número copiando o formato de uma matriz existente


In [ ]:
np.full_like(c, 4)

### Criar ranges

#### arange

Método que retorna elementos igualmente espaçados num step (por padrão, 1) dentro de um certo intervalo.


In [ ]:
np.arange(0, 10)

Step diferente de 1:


In [ ]:
np.arange(0, 5, 0.1)

#### linspace

Parecido com o arange, mas você diz quantos pontos você quer e o intervalo e ele define o espaçamento linear


In [ ]:
np.linspace(0, 100, num=10, retstep=True)


#### logspace
Retorna números espaçados igualmente na escala log.


In [ ]:
np.logspace(0, 100, num=10, base=2.0)

### Funções matemáticas
O NumPy oferece diversas funções matemáticas clássicas, como exponencial, logaritmo, seno, cosseno etc. Essas funções são aplicadas a todos os elementos do array
##### Função seno:

In [ ]:
np.sin(a)

##### Função cosseno

In [ ]:
np.cos(a)

#### Exponencial

In [ ]:
np.exp(a)

#### Log

In [ ]:
np.log(a)

### Funcionalidades extras
#### Carregar dados de um arquivo

Vamos supor que temos um arquivo data.txt com o seguinte conteúdo:

1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5 <br>
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12 <br>
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88 <br>

Podemos gerar uma matriz a partir desse arquivo da seguinte forma:


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

O primeiro argumento é o nome do arquivo.

No segundo argumento, delimiter, você especifica o que separa cada número individualmente no arquivo. Nesse caso é a vírgula, mas podería ser ;, espaços, ou tabs.

Podemos notar também que o numpy converteu para float nossos números, apesar de todos serem inteiros. Ele faz isso como uma medida preventiva dado que ele não sabe ao ler o arquivo qual tipo de dado que é.

Podemos importar os dados com um formato especificado usando o argumento `dtype='int'` ou podemos converter manualmente para inteiro usando a função astype:

In [ ]:
filedata.astype('int32')

Também podemos avisar o numpy quais são nossas colunas de interesse com o argumento `usecols`

In [ ]:
np.genfromtxt('data.txt', delimiter=',', usecols=[0,1,2,3], dtype='int')

Podemos também salvar uma matriz de uma forma mais otimizada não textual (binária) para uso futuro.

Isso gera um arquivo binário que inclusive salva o tipo de dado, nesse caso, int32.

Quando lido, vai converter corretamente o tipo daquele dado.



In [ ]:
np.save('data_saved', filedata.astype('int32'))


Para ler os dados que acabamos de salvar, basta usar o `np.load`:


In [ ]:
np.load('data_saved.npy')

### Álgebra Linear

Da definição do Wikipédia:

    Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.

O numpy nos permite executar diversas diversas operações de álgebra linear, mostradas a seguir:


In [ ]:
a = np.ones((2, 3))
print(a)
print()

b = np.full((3, 2), 2)
print(b)
print()

c = np.identity(5)
print(c)

##### Transposição

<img src="transposicao.png"  style="width: 400px" />

A operação de transposição pode ser feita da seguinte forma:

In [ ]:
np.transpose(a)

Ou acessando o atributo T:

In [ ]:
a.T

#### Multiplicação de matrizes

A tradicional multiplicação de matrizes, como mostra a imagem abaixo:

<img src="multiplicacao.gif"  style="width: 400px" />

pode ser feita no numpy simplesmente chamando `matmul`


In [ ]:
np.matmul(a, b)

Operador `@` executa a função anterior:


In [ ]:
a @ b

Se utilizarmos o símbolo * teremos a múltiplicação elemento à elemento e precisaremos de matrizes de mesmo tamanho

In [ ]:
a = np.array([[1, 2], [3, 2]])
b = np.array([[4, 5], [2, 1]])
print(a)
print()
print(b)
a * b

Outras funcções de Álgebra Linear: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

    Trace
    Decomposição de vetores
    Autovalor/autovetor
    Norma da Matriz
    Inversa
    Etc...


Referências   <br>
<a href="https://github.com/numpy/numpy" target="_blank">NumPy GitHub</a>  <br>
<a href="https://docs.scipy.org/doc/numpy/reference/" target="_blank">Documentação oficial</a>   <br>
<a href="https://docs.scipy.org/doc/numpy/reference/routines.math.html" target="_blank">Funções matemáticas</a>   <br>
<a href="https://docs.scipy.org/doc/numpy/reference/routines.linalg.html" target="_blank">Funções de Álgebra Linear</a>   <br>
<a href="http://www.opl.ufc.br/pt/post/numpy/" target="_blank">Outros</a> 
    

## Outros tópicos
* Broadcasting: operações com vetores de dimensões distintas

<a href="http://www.opl.ufc.br/pt/post/numpy/" target="_blank">Referência</a> 

## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [151]:
array = np.arange(1,10)
array[array%2==1] 

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [152]:
np.where(array%2==1,0,array)

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [3]:
import numpy as np

In [8]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
temp = np.genfromtxt(url, delimiter=',')
iris = temp[:10,:4]
iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [13]:
iris[:,0].mean()

4.859999999999999

In [16]:
np.median(iris[:,0])

4.9

In [17]:
iris[:,0].std()

0.2764054992217051

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [28]:
iris[:,2]>1.5

array([False, False, False, False, False,  True, False, False, False,
       False])

In [25]:
iris[:,0]<5

array([False,  True,  True,  True, False, False,  True, False,  True,
        True])

6 - Esse dataset possui nans?

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [ ]:
#np.set_printoptions(suppress=True) 

# np.printoptions

#with np.printoptions(precision=2):
#    print(nova_tabela)
#printa os números com precisão 2

#usar np.set_printoptions(precision=4)

## Mais coisas interessantes...


#### Tipo de dado e tamanho

Na sessão Checando o tipo de dados do array já foi dito dos tipos de dados, mas agora falaremos da diferença de tamanhos que isso ocupa na memória.

Então, temos as variáveis a e b criadas anteriormente com os seguintes tipos:


In [ ]:
a.dtype

In [ ]:
b.dtype


Por padrão, se o python instalado é 64 bits, ele irá criar tipos int ou float de 64 bits. Caso seu python fosse 32 bits, seria int32 e float32.

Vamos criar uma outra array, a16, com o tipo inteiro de 16 bits.


In [ ]:
a16 = np.array([1, 2, 3], dtype=np.int16)
a16


Note que por ser um tipo diferente do padrão, ele ressalta ao imprimir.

Para descobrir quanto cada elemento individualmente ocupa na memória, podemos acessar o atributo itemsize:


In [ ]:
a.itemsize


Ele retorna 8 e não 64! Isso é porque ele já converteu os bits para bytes. Bytes é o conjunto de 8 bits.

Logo:

$ 64/8=8 $

Já nosso array int16, temos:


In [ ]:
a16.itemsize

Uma vez que:

$ 16/8 = 2 $

In [ ]:
# quantidade de elementos total
a.size

Quantidade de elementos vezes o tamanho de cada elemento nos dará o tamanho total de bytes que o array inteiro ocupa:


In [ ]:
a.size * a.itemsize


Mas ao invés de calcular isso, podemos simplesmente acessar o atributo `nbytes`, que já é o tamanho total de bytes ocupado pelo array:


In [ ]:
a.nbytes

**Observação**

Geralmente não é necessário reduzir o número de bits a não ser que você tenha certeza que um tamanho reduzido vai atender sua necessidade e você quer ser extremamente eficiente.
